# Dockerfile for deploying vite + vue3 + typescript on a server
FROM node:latest

# Install dependencies to serve the app
RUN npm install -g serve

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose port 5173
EXPOSE 5173

# Build the app
RUN npm run build

# Run the app
CMD [ "serve", "-s", "dist", "-l", "5173" ]
